name: map_track_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_background: 1.3.0
  flutter_local_notifications: ^18.0.1
  focused_menu: ^1.0.5
  geolocator: ^13.0.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  widget_to_marker: ^1.0.6

dev_dependencies:
  build_runner: 2.4.11
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/json/dark_mode.json
    - assets/images/
  uses-material-design: true
